worker:
  name: "worker"
  healthCheck:
    interval: 10000
    timeout: 5000
  converters:
    key: "key-converter"
    value: "value-converter"
  processors: 
    01: 
      name: "processor-name"
      settings: { } #processor specific settings
  faultTolerance:
    batches:
      size: 100
      interval: 1000
      parallelism: 1
    retries:
      attempts: 3
      interval: 1000
    errors:
      tolerance: none #none, all, data
      topic: dead-letter-topic
    eof:
      enabled: false
      topic: end-of-file-topic
  plugins:
    location: "path-to-plugins"
    initializers: # one or more initializers
      plugin-name:
        folder: "path-to-initializer"
        assembly: "assembly-name"
        class: "class-name"
  topics: # internal topics only go here
    topic-name:
      purpose: "purpose" #none, config, command, sink, source
      converters: 
        key: "key-converter"
        value: "value-converter"
      processors:
        01: 
          name: "processor-name"
          settings: { } #processor specific settings
  connectors:
    connector-name:
      overrides: # topic level overrides
        topic-name:
          converters:
            key: "key-converter"
            value: "value-converter"
          processors:
            01: 
              name: "processor-name"
              settings: { } #processor specific settings
              
      groupId: "group-id"
      disabled: false
      paused: false
      tasks: 3
      topics:
        - topic1
        - topic2
      faultTolerance:
        batches:
          size: 100
          interval: 1000
          parallelism: 1
        retries:
          attempts: 3
          interval: 1000
        errors:
          tolerance: none #none, all, data
          topic: dead-letter-topic
        eof:
          enabled: false
          topic: end-of-file-topic
      plugin:
        type: "type" #source, sink
        name: "plugin-name"
        handler: "handler-name"
        strategy: 
          name: "strategy-name"
          selector: "selector-name"
        properties: 
          # postgresql sink properties
          host: "localhost"
          port: 5432
          database: "database"
          userId: "user"
          password: "password"
          # sink properties
          schema: "public"
          table: "table"
          lookup: "lookup"
          filter: "filter"
          # source properties
          changelog:  # merge this with the sink properties
            schema: "public"
            table: "table"
          commands:
            command-1:
              schema: "public"
              table: "table"
              keys: ["key-1", "key-2"]
              filters: ["filter-1", "filter-2"]
              snapshot: # do i need enabled flag or can this just contain the key?
                enabled: true
                key: "key"
  