name: Build and Publish

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore --configfile nuget.config
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

  publish-nuget:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Determine version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="1.0.0-preview.${GITHUB_RUN_NUMBER}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
        
    - name: Restore dependencies
      run: dotnet restore --configfile nuget.config
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        
    - name: Build Kafka.Connect.Plugin
      run: |
        cd src/Kafka.Connect.Plugin
        dotnet build /p:Version=${{ steps.version.outputs.VERSION }} --configuration Release --no-restore
        
    - name: Pack Kafka.Connect.Plugin
      run: |
        cd src/Kafka.Connect.Plugin
        dotnet pack /p:Version=${{ steps.version.outputs.VERSION }} --configuration Release --no-build --no-restore --output ./nupkgs
        
    - name: Publish Kafka.Connect.Plugin to GitHub Packages
      run: |
        cd src/Kafka.Connect.Plugin
        dotnet nuget push ./nupkgs/Kafka.Connect.Plugin.${{ steps.version.outputs.VERSION }}.nupkg \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          
    - name: Build Plugins
      run: |
        cd src/Plugins
        dotnet build /p:Version=${{ steps.version.outputs.VERSION }} --configuration Release --no-restore
        
    - name: Pack Plugins
      run: |
        cd src/Plugins
        dotnet pack /p:Version=${{ steps.version.outputs.VERSION }} --configuration Release --no-build --no-restore --output ./nupkgs
        
    - name: Publish Plugins to GitHub Packages
      run: |
        cd src/Plugins
        for package in ./nupkgs/*.${{ steps.version.outputs.VERSION }}.nupkg; do
          dotnet nuget push "$package" \
            --api-key ${{ secrets.GITHUB_TOKEN }} \
            --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        done

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=raw,value=latest,enable={{is_default_branch}}
          
    - name: Determine version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
        else
          VERSION="1.0.0-preview.${GITHUB_RUN_NUMBER}"
        fi
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BUILD_VERSION=${{ steps.version.outputs.VERSION }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME=${{ github.actor }}
          PUBLISH=true