name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore 
    - name: Test
      run: dotnet test src/Tests/Kafka.Connect.UnitTests/Kafka.Connect.UnitTests.csproj --no-build --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --results-directory ./coverage  || true 
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: tests
        path: "**/test-results.trx"
        reporter: dotnet-trx
        fail-on-error: true
    - name: Copy Coverage Report
      run: cp coverage/**/coverage.cobertura.xml coverage.cobertura.xml
    - name: Code Coverage
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: false
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Coverage Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
